### ISSUE TITLE
部署在VPS上启动后无法访问

### ISSUE THREAD

**Issue by syuez** [dream2023/fgen-cli#1]
运行在3389端口
`pm2 start fgen --node-args="p=3389"` 
使用 ps 查看进程
 `node p=3389 /usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js`
但是netstat 查看端口监听，没有3389端口，浏览器访问 `ip+port` 失败

**Comment by dream2023** [comment]
讲过查证，是pm2的问题，这里换了个工具，你先试试：

https://github.com/dream2023/fgen-cli/wiki/%E5%A6%82%E4%BD%95%E4%BB%A5%E5%AE%88%E6%8A%A4%E8%BF%9B%E7%A8%8B%E6%96%B9%E5%BC%8F%E5%90%AF%E5%8A%A8fgen-cli

**Comment by syuez** [comment]
@dream2023 提示`script /root/fgen does not exist`是什么原因，已经装了`npm install -g fgen-cli`

**Comment by dream2023** [comment]
你先 

```bash
forever stopall
```

```bash
forever start $(which fgen) -p 9090 # 你自己的端口
```

**Comment by syuez** [comment]
@dream2023 可以了，谢谢！
